In [1]:
from itertools import count

import pandas as pd
import numpy as np
import sklearn as skl

data = pd.read_csv('friction_place_data_2024.csv')
data.head()

,var.1,var.2,var.3,var.4,var.5,var.6,var.7,var.8,var.9,env.mbar,env.temp,env.hum,mat.2,mat.1,mat.3,Test.Result
0,0.573241,333.820198,22.988291,2,82,1.277546,2,21.443323,0.797869,995.143036,9,0.49,8.489696,14,154.875558,True
1,0.653573,280.281445,23.768343,2,89,1.246388,1,19.109389,-1.986141,1120.052376,9,0.30,6.717008,14,146.448811,False
2,0.632798,291.985294,21.991274,1,79,1.199507,2,19.667494,1.205539,934.854224,18,0.19,7.357749,20,112.030126,True
3,0.645263,269.346537,22.533471,2,88,1.232027,1,21.296443,1.415573,950.705889,16,0.29,6.498423,15,181.999714,False
4,0.649418,284.702282,22.029858,1,90,1.221646,1,20.991244,1.489283,1018.912404,18,0.47,3.609809,14,114.384407,False

In [20]:
tf_counts = data['Test.Result'].value_counts().to_numpy()

round((tf_counts[0] / (tf_counts[0] + tf_counts[1])*100), 1)

np.float64(58.8)

In [18]:
data['Test.Result'].value_counts()

Test.Result
False    120
True      84
Name: count, dtype: int64

In [24]:
true_data = data[data['Test.Result'] == True]
true_data

,var.1,var.2,var.3,var.4,var.5,var.6,var.7,var.8,var.9,env.mbar,env.temp,env.hum,mat.2,mat.1,mat.3,Test.Result
0,0.573241,333.820198,22.988291,2,82,1.277546,2,21.443323,0.797869,995.143036,9,0.49,8.489696,14,154.875558,True
2,0.632798,291.985294,21.991274,1,79,1.199507,2,19.667494,1.205539,934.854224,18,0.19,7.357749,20,112.030126,True
5,0.596787,286.427233,23.012245,2,82,1.190834,3,20.841394,-0.245496,965.574468,13,0.14,2.441738,17,166.278666,True
6,0.635568,273.171223,22.976584,2,77,1.213512,2,19.873665,1.572291,1028.417996,14,0.32,8.667039,12,160.646588,True
10,0.570471,274.616641,23.654827,2,73,1.257708,2,20.724917,2.657529,937.547442,10,0.53,9.769286,16,164.720964,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,0.596787,295.084515,22.087821,1,89,1.210007,2,20.124706,-1.052114,1101.336857,10,0.68,8.096781,15,174.890590,True
192,0.562161,288.201597,22.045827,2,80,1.240743,2,19.665618,0.136932,898.170337,9,0.33,6.399320,15,129.537265,True
198,0.589861,275.992110,22.090845,2,71,1.285964,3,19.466347,0.078283,1042.025462,8,0.69,3.409613,10,128.666577,True
200,0.653573,258.855037,22.999826,1,71,1.240224,3,21.472308,-0.405009,889.545493,18,0.52,3.371586,19,144.300896,True
201,0.618947,297.856826,22.987981,2,70,1.216177,1,19.301963,0.027646,1006.672664,16,0.36,3.358850,17,199.815498,True

In [28]:
round(true_data['mat.2'].mean(axis=0),1)

np.float64(6.2)